### ISSUE TITLE
The input images in the paper are inconsistent.

### ISSUE THREAD

**Issue by zhangzjn** [bytedance/TextHarmony#5]
I attempted to infer the visual text editing capabilities of TextHarmony and found that the input images in Fig. 1 and Fig. 6 of the paper are inconsistent, as shown below. Could you please explain the reason for this? Is it possible that some implementation details were omitted? 
<img width="1228" alt="Clipboard_Screenshot_1732711363" src="https://github.com/user-attachments/assets/e6f62f07-c56e-4c14-8689-2afb0398f042">

**Comment by prefixRAINSTARsuffix** [comment]
@zhangzjn Figure 1 is only a Sketch Map，which has no relation to the performance.

**Comment by prefixRAINSTARsuffix** [comment]
@zhangzjn It looks like the right image in Figure 1 is the original image. I think I mistakenly reversed them while drawing the figure.
