### ISSUE TITLE
Capability test for visual text editing

### ISSUE THREAD

**Issue by zhangzjn** [bytedance/TextHarmony#6]
I am conducting a capability test for visual text editing. When using the following input for the visual text editing capability test, the model fails to maintain character replacement in the edited region consistently across different prompts. The generated images appear darker, and some details are altered or distorted, which significantly differs from the results shown in Fig. 6. Could you please explain the possible reasons for this discrepancy? Additionally, could the authors provide the inference code for visual text editing? Thank you very much.
<img width="1761" alt="Clipboard_Screenshot_1732711611" src="https://github.com/user-attachments/assets/1d4c59fb-bfcc-407e-80cd-f771e0b32434">

**Comment by zhangzjn** [comment]
Also, when I change to the following prompt, the result is similar.
`Generate an image according to the caption. \"Keep Focused\".`
![ps_image](https://github.com/user-attachments/assets/826662ce-c8c3-4a67-9094-3e259866c910)

**Comment by prefixRAINSTARsuffix** [comment]
@zhangzjn The prompt for visual text editing should be " Fill the masked part in this image with <text>", as depicted in Table 6.

**Comment by zhangzjn** [comment]
I change to the following prompt, but the result is similar.
`Generate an image according to the caption. \"Keep Focused\".` Could you provide more scripts to realize this function? Thanks a lot.
![ps_image](https://github.com/user-attachments/assets/2214cda6-0398-407e-a94b-7292191d0e0c)

**Comment by zhangzjn** [comment]
@prefixRAINSTARsuffix 
I change to the following prompt `Fill the masked part in this image with \"Keep Focused\".`, but the result is similar. Could you provide more scripts to realize this function? Thanks a lot. 
![ps_image](https://github.com/user-attachments/assets/fd3f6ea0-b357-4413-9a5e-e179637591d0)

**Comment by prefixRAINSTARsuffix** [comment]
@zhangzjn 
Try this.
"""
{
        "sentences": [
            "Fill the masked part in this image with \"Keep Focused\".", 
            ""
        ], 
        "images": [
            "TextHarmony/docs/examples/image.jpg", 
            "TextHarmony/docs/examples/all_zero.jpg"
        ], 
        "sentence_ixs": [0, 1], 
        "image_first": [true, true], 
        "generate_mode": "generate_images", 
        "num_iter": 1
    }
"""
The results may not be very perfect like AnyText, since the NED of TextHarmony is only 0.75 compared to AnyText(0.88).

**Comment by zhangzjn** [comment]
@prefixRAINSTARsuffix 
Thank you for your prompt response. My current configuration is exactly the same as the one mentioned. 

I appreciate the clarification, which has provided me with a clearer understanding of the strengths and weaknesses of the algorithm. This will be very helpful for our future work.

**Comment by fx-hit** [comment]
> @prefixRAINSTARsuffix I change to the following prompt `Fill the masked part in this image with \"Keep Focused\".`, but the result is similar. Could you provide more scripts to realize this function? Thanks a lot. ![ps_image](https://private-user-images.githubusercontent.com/26211183/390480425-fd3f6ea0-b357-4413-9a5e-e179637591d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NjIzMzgsIm5iZiI6MTczMjc2MjAzOCwicGF0aCI6Ii8yNjIxMTE4My8zOTA0ODA0MjUtZmQzZjZlYTAtYjM1Ny00NDEzLTlhNWUtZTE3OTYzNzU5MWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDAyNDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZDM2MTI0YzhkMjZmZjQzZmEyYTZlYzA2NmEzYWY4NTMyN2I0YjI3OGRjZGVkMmIwZWQyMWMwMThjYzI4ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gK9b1ozdU4j8S91PgMM4NOdnxBf-hSWkLBV476OwpvU)

In addition to the mask area being edited, other parts have not been well preserved, especially the text with smaller font sizes has become unrecognizable.
 If post-processing is done with mask*gen_img + (1-mask)*ori_img, will the edited area have significant inconsistencies with the rest of the image?
